apiVersion: v1
kind: Secret
metadata:
  name: secret-volume-demo
spec:
  containers:
    - name: nodejs-app-container
      image: 474717635696.dkr.ecr.us-east-1.amazonaws.com/nodejs/app01:${IMAGE_TAG}
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret-volume"
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: new-pass-2
    